<?php $pageTitle = 'Customer directory'; ?>
<section class="owner-module">
    <header class="module-heading"><div><span class="eyebrow section-eyebrow">Customer records</span><h1>Customer directory</h1><p>Find customer contact details and review their reservation history without changing the original booking records.</p></div><span class="module-total"><?= count($customers) ?> results</span></header>
    <form method="get" action="<?= rc_e(rc_endpoint()) ?>" class="customer-search-form"><input type="hidden" name="page" value="customers"><label class="sr-only" for="customer-search">Search customers</label><input id="customer-search" type="search" name="q" value="<?= rc_e($customerSearch) ?>" placeholder="Name, email, mobile, or customer ID"><button class="button" type="submit">Search</button><?php if ($customerSearch !== ''): ?><a class="button button-secondary" href="<?= rc_url('customers') ?>">Clear</a><?php endif; ?></form>
    <section class="surface"><div class="surface-heading"><h2>Customers</h2><span>Most recently registered first · maximum 500 shown</span></div>
        <?php if ($customers): ?><div class="table-wrap"><table><thead><tr><th>Customer</th><th>Contact</th><th>Address</th><th>Registered</th><th>Reservations</th><th>Paid to date</th><th>Action</th></tr></thead><tbody><?php foreach ($customers as $customer): ?><tr>
            <td><?= rc_e($customer['full_name']) ?><small>Customer #<?= (int) $customer['customer_id'] ?></small></td><td><?= rc_e($customer['email']) ?><small><?= rc_e($customer['contact_number']) ?></small></td><td><?= nl2br(rc_e($customer['address'] ?: 'Not provided')) ?></td><td><?= rc_e($customer['created_at']) ?></td><td><?= (int) $customer['order_count'] ?></td><td><?= rc_money(rc_cents($customer['amount_paid'])) ?></td><td><a class="text-link" href="<?= rc_url('orders', ['q' => $customer['full_name']]) ?>">View orders</a><details class="customer-edit-details"><summary>Edit contact</summary><form method="post" action="<?= rc_e(rc_endpoint()) ?>" data-confirm="Save updated contact details for <?= rc_e($customer['full_name']) ?>? Existing reservations keep their saved customer details."><?= rc_csrf_field() ?><input type="hidden" name="action" value="owner-customer-profile"><input type="hidden" name="customer_id" value="<?= (int) $customer['customer_id'] ?>"><label>Full name<input class="input-field" name="full_name" maxlength="120" value="<?= rc_e($customer['full_name']) ?>" required></label><label>Email<input class="input-field" name="email" type="email" maxlength="254" value="<?= rc_e($customer['email']) ?>" required></label><label>Mobile<input class="input-field" name="contact_number" maxlength="30" value="<?= rc_e($customer['contact_number']) ?>" required></label><label>Address<textarea class="input-field" name="address" maxlength="500"><?= rc_e($customer['address']) ?></textarea></label><button class="button button-secondary" type="submit">Save contact</button></form></details></td>
        </tr><?php endforeach; ?></tbody></table></div><?php else: ?><div class="empty-state"><strong>No customers match this search</strong>Try another name, email, mobile number, or customer ID.</div><?php endif; ?>
    </section>
</section>
