<?php
$pageTitle = 'Digital catering menu';
$selectedCategory = trim((string) ($_GET['category'] ?? ''));
$selectedPackageType = (string) ($selectedPackageType ?? '');
$showPackagesOnly = $selectedPackageType !== '';
$fallbackPackageImage = 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=800&q=78';
$fallbackDishImage = 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=78';
$unitLabels = ['tray_25_35pax'=>'Tray · serves 25–35','per_pc'=>'Per piece','per_box'=>'Per box','per_tray'=>'Per tray','per_layer'=>'Per layer','per_slice'=>'Per slice','per_person'=>'Per person','each'=>'Each'];
?>
<section class="page-intro"><div class="intro-inner"><span class="eyebrow">Current catering offerings</span><h1>Digital menu</h1><p>Browse individual dishes or explore food packages built from selections in our kitchen.</p></div></section>
<section class="catalog" id="catalog"><aside class="sidebar"><h2>Categories</h2><div class="filter-list"><a class="filter-button <?= !$showPackagesOnly && $selectedCategory === '' ? 'active' : '' ?>" href="<?= rc_url('menu') ?>">All dishes</a><?php foreach ($categories as $category): ?><a class="filter-button <?= !$showPackagesOnly && strcasecmp($selectedCategory, $category) === 0 ? 'active' : '' ?>" href="<?= rc_url('menu', ['category' => $category]) ?>"><?= rc_e($category) ?></a><?php endforeach; ?></div><h2>Food packages</h2><div class="filter-list"><a class="filter-button <?= $selectedPackageType === 'packed_meal' ? 'active' : '' ?>" href="<?= rc_url('menu', ['package_type' => 'packed_meal']) ?>">Packed Meals</a><a class="filter-button <?= $selectedPackageType === 'buffet' ? 'active' : '' ?>" href="<?= rc_url('menu', ['package_type' => 'buffet']) ?>">Buffet</a></div><h2>Account</h2><div class="filter-list"><a class="filter-button" href="<?= $user ? rc_url('dashboard') : rc_url('login') ?>">Reservations &amp; status</a></div></aside>
<div>
    <?php if (!$selectedCategory): ?><div class="catalog-top"><h2><?= $selectedPackageType === 'packed_meal' ? 'Packed Meals' : ($selectedPackageType === 'buffet' ? 'Buffet Packages' : 'Food packages') ?></h2><span class="result-count"><?= count($packages) ?> active</span></div>
    <?php if ($packages): ?><div class="product-grid"><?php foreach ($packages as $package): $stmt = rc_db()->prepare("SELECT DISTINCT mi.name FROM package_items pi JOIN menu_items mi ON mi.id=pi.menu_item_id JOIN catering_packages cp ON cp.package_id=pi.package_id WHERE pi.package_id=? AND mi.is_active=1 AND (cp.package_type<>'buffet' OR mi.name=SUBSTRING(pi.option_group,11)) ORDER BY pi.option_group, mi.name"); $stmt->execute([$package['package_id']]); $optionNames = $stmt->fetchAll(PDO::FETCH_COLUMN); $packageImage = (string) ($package['image_url'] ?: $fallbackPackageImage); ?>
        <article class="product-card"><div class="product-image-wrap"><img class="product-image" src="<?= rc_e(rc_asset_url($packageImage)) ?>" alt="<?= rc_e($package['package_name']) ?>" loading="lazy"><span class="product-category"><?= rc_e($package['minimum_guests']) ?><?= !empty($package['maximum_guests']) ? '–' . rc_e($package['maximum_guests']) : '+' ?> PAX</span></div><div class="product-info"><h3><?= rc_e(($package['set_name']??'') ?: $package['package_name']) ?></h3><p><?= rc_e($package['description'] ?: 'A catering package available for event reservation.') ?></p><div class="diet-tags"><span class="diet-tag"><?= rc_e(ucwords(str_replace('_',' ',(string)($package['package_type']??'custom')))) ?></span><span class="diet-tag"><?= $package['price_type'] === 'Per Person' ? 'Per person' : 'Package price' ?></span></div><div class="product-bottom"><span class="price"><?= rc_money(rc_cents($package['package_price'])) ?><?= $package['price_type'] === 'Per Person' ? ' / person' : '' ?></span><button class="add-button" type="button" data-dialog-title="<?= rc_e($package['package_name']) ?>" data-dialog-text="<?= rc_e(implode(', ', $optionNames) ?: 'Food selections are being prepared by owner.') ?>">View dishes</button></div><a class="text-link inline-link" href="<?= rc_url('reservation', ['package' => $package['package_id']]) ?>">Customize and reserve →</a></div></article>
    <?php endforeach; ?></div><?php else: ?><div class="empty-state"><strong>No active packages yet</strong>Food packages will appear here when they are available.</div><?php endif; ?>
    <?php endif; ?>
    <?php if (!$showPackagesOnly): ?><div class="catalog-top section-top"><h2><?= $selectedCategory ? rc_e($selectedCategory) . ' dishes' : 'Individual dishes' ?></h2><span class="result-count"><?= count($items) ?> active</span></div>
    <?php if ($items): ?><div class="product-grid"><?php foreach ($items as $item): $dishImage = (string) ($item['image_url'] ?: $fallbackDishImage); ?>
        <article class="product-card"><div class="product-image-wrap"><img class="product-image" src="<?= rc_e(rc_asset_url($dishImage)) ?>" alt="<?= rc_e($item['name']) ?>" loading="lazy"><span class="product-category"><?= rc_e($item['category'] ?: 'Dish') ?></span></div><div class="product-info"><h3><?= rc_e($item['name']) ?></h3><p><?= rc_e($item['description'] ?: 'Prepared fresh for your event.') ?></p><div class="product-bottom"><span class="price"><?= rc_money(rc_cents($item['price'])) ?><small> · <?= rc_e($unitLabels[$item['unit_type']??'tray_25_35pax'] ?? 'Each') ?></small></span><button class="add-button" type="button" data-dialog-title="<?= rc_e($item['name']) ?>" data-dialog-text="<?= rc_e($item['description'] ?: 'Menu selection') ?>">Details</button></div><a class="text-link inline-link" href="<?= rc_url('reservation', ['order_type' => 'alacarte']) ?>">Choose trays &amp; quantities →</a></div></article>
    <?php endforeach; ?></div><?php else: ?><div class="empty-state"><strong>No active dishes</strong>Individual dishes will appear here when they are available.</div><?php endif; ?><?php endif; ?>
</div></section>
