<?php $pageTitle = 'Individual food menu'; ?>
<section class="owner-module">
    <header class="module-heading"><div><span class="eyebrow section-eyebrow">Customer digital menu</span><h1>Menu management</h1><p>Add and manage individual dishes. Set each dish’s price, description, and photo.</p></div><span class="module-total"><?= count($items) ?> dishes</span></header>
    <nav class="menu-admin-tabs" aria-label="Menu sections"><a class="active" aria-current="page" href="<?= rc_url('menu-admin') ?>">Individual food menu</a><a href="<?= rc_url('packages-admin') ?>">Food packages</a></nav>
    <div class="owner-management-grid">
        <section class="surface"><div class="surface-heading"><h2>Add a dish</h2><span>Prices in PHP</span></div>
            <form method="post" enctype="multipart/form-data" action="<?= rc_e(rc_endpoint()) ?>" class="form-stack"><?= rc_csrf_field() ?><input type="hidden" name="action" value="menu-item">
                <label>Name<input class="input-field" name="name" maxlength="255" required></label><label>Category<input class="input-field" name="category" maxlength="50" placeholder="Main dishes, sides, desserts" required></label><label>Description<textarea class="input-field" name="description" maxlength="5000"></textarea></label><label>Price (PHP)<input class="input-field" name="price" type="number" min="0.01" step="0.01" required></label><label>Serving unit<select class="input-field" name="unit_type"><option value="tray_25_35pax">Tray · serves 25–35</option><option value="per_pc">Per piece</option><option value="per_box">Per box</option><option value="per_tray">Per tray</option><option value="per_layer">Per layer</option><option value="per_slice">Per slice</option><option value="per_person">Per person</option><option value="each">Each</option></select></label><label>Dish role<select class="input-field" name="component_type"><option value="alacarte">Individual / snack</option><option value="main_dish">Main dish</option><option value="side_dish">Side dish</option><option value="dessert">Dessert</option><option value="salad">Salad</option><option value="rice">Rice</option><option value="drink">Drink</option></select></label><label>Dish photo (optional)<input class="input-field" name="image_file" type="file" accept="image/jpeg,image/png,image/webp"></label><label>Or image URL<input class="input-field" name="image_url" maxlength="1000" placeholder="https://…"></label>
                <div class="check-row"><label><input type="checkbox" name="is_vegan"> Vegan</label><label><input type="checkbox" name="is_gluten_free"> Gluten-free</label></div><button class="button" type="submit">Add dish</button>
            </form>
        </section>
        <section class="surface"><div class="surface-heading"><h2>Individual dishes</h2><span><?= count($items) ?> records</span></div>
            <?php if ($items): ?><div class="package-admin-list"><?php foreach ($items as $item): $itemId = (int) $item['id']; $image = (string) ($item['image_url'] ?? ''); ?>
                <details class="package-admin-entry"><summary><span><strong><?= rc_e($item['name']) ?></strong><small><?= rc_e($item['category']) ?> · <?= rc_money(rc_cents($item['price'])) ?> · <?= $item['is_active'] ? 'Active' : 'Archived' ?></small></span><b>Edit</b></summary>
                    <form method="post" enctype="multipart/form-data" action="<?= rc_e(rc_endpoint()) ?>" class="form-stack"><?= rc_csrf_field() ?><input type="hidden" name="action" value="update-item"><input type="hidden" name="id" value="<?= $itemId ?>">
                        <label>Name<input name="name" maxlength="255" value="<?= rc_e($item['name']) ?>" required></label><label>Category<input name="category" maxlength="50" value="<?= rc_e($item['category']) ?>" required></label><label>Description<textarea name="description" maxlength="5000"><?= rc_e($item['description']) ?></textarea></label><label>Price (PHP)<input name="price" type="number" min="0.01" step="0.01" value="<?= rc_e($item['price']) ?>" required></label><label>Serving unit<select name="unit_type"><?php foreach (['tray_25_35pax'=>'Tray · serves 25–35','per_pc'=>'Per piece','per_box'=>'Per box','per_tray'=>'Per tray','per_layer'=>'Per layer','per_slice'=>'Per slice','per_person'=>'Per person','each'=>'Each'] as $value=>$label): ?><option value="<?= $value ?>" <?= ($item['unit_type']??'tray_25_35pax')===$value?'selected':'' ?>><?= rc_e($label) ?></option><?php endforeach; ?></select></label><label>Dish role<select name="component_type"><?php foreach (['alacarte'=>'Individual / snack','main_dish'=>'Main dish','side_dish'=>'Side dish','dessert'=>'Dessert','salad'=>'Salad','rice'=>'Rice','drink'=>'Drink'] as $value=>$label): ?><option value="<?= $value ?>" <?= ($item['component_type']??'alacarte')===$value?'selected':'' ?>><?= rc_e($label) ?></option><?php endforeach; ?></select></label>
                        <?php if ($image !== ''): ?><img class="menu-admin-preview" src="<?= rc_e(rc_asset_url($image)) ?>" alt="Current photo of <?= rc_e($item['name']) ?>"><?php endif; ?><label>Choose a photo<input name="image_file" type="file" accept="image/jpeg,image/png,image/webp"></label><label>Or image URL<input name="image_url" maxlength="1000" value="<?= preg_match('~^https?://~i', $image) ? rc_e($image) : '' ?>" placeholder="Keep current photo or add a URL"></label><?php if ($image !== ''): ?><label><input type="checkbox" name="remove_image" value="1"> Remove current photo</label><?php endif; ?>
                        <label><input type="checkbox" name="is_vegan" <?= $item['is_vegan'] ? 'checked' : '' ?>> Vegan</label><label><input type="checkbox" name="is_gluten_free" <?= $item['is_gluten_free'] ? 'checked' : '' ?>> Gluten-free</label><button class="button button-secondary" type="submit">Save dish</button>
                    </form>
                    <form method="post" action="<?= rc_e(rc_endpoint()) ?>" data-confirm="<?= $item['is_active'] ? 'Archive' : 'Restore' ?> <?= rc_e($item['name']) ?>? Existing reservations will be preserved."><?= rc_csrf_field() ?><input type="hidden" name="action" value="toggle-item"><input type="hidden" name="id" value="<?= $itemId ?>"><button class="text-link danger-link" type="submit"><?= $item['is_active'] ? 'Archive dish' : 'Restore dish' ?></button></form>
                </details>
            <?php endforeach; ?></div><?php else: ?><div class="empty-state"><strong>No dishes yet</strong>Add individual dishes here. Photos can be added or changed later.</div><?php endif; ?>
        </section>
    </div>
</section>
