<?php $pageTitle = 'Orders'; ?>
<section class="owner-module">
    <header class="module-heading"><div><span class="eyebrow section-eyebrow">Reservation management</span><h1>Orders and reservations</h1><p>Review customer and event details, package choices, payment history, and reservation status.</p></div><span class="module-total"><?= count($orders) ?> results</span></header>
    <form class="order-filter-bar" method="get" action="<?= rc_e(rc_endpoint()) ?>">
        <input type="hidden" name="page" value="orders">
        <label class="filter-search">Search<input type="search" name="q" value="<?= rc_e($filters['q']) ?>" placeholder="Name, phone, package, reservation ID"></label>
        <label>Status<select name="status"><option value="">All statuses</option><?php foreach (['Pending','Confirmed','Processing','Completed','Cancelled','Rejected'] as $status): ?><option value="<?= rc_e($status) ?>" <?= $filters['status'] === $status ? 'selected' : '' ?>><?= rc_e($status) ?></option><?php endforeach; ?></select></label>
        <label>Payment<select name="payment"><option value="">All payments</option><?php foreach (['Pending','Partially Paid','Paid in Full'] as $payment): ?><option value="<?= rc_e($payment) ?>" <?= $filters['payment'] === $payment ? 'selected' : '' ?>><?= rc_e($payment) ?></option><?php endforeach; ?></select></label>
        <label>Event date<select name="date"><option value="">Any date</option><?php foreach (['today'=>'Today','upcoming'=>'Upcoming','week'=>'This week','month'=>'This month'] as $key => $label): ?><option value="<?= rc_e($key) ?>" <?= $filters['date'] === $key ? 'selected' : '' ?>><?= rc_e($label) ?></option><?php endforeach; ?></select></label>
        <label>From<input type="date" name="from" value="<?= rc_e($filters['from']) ?>"></label><label>To<input type="date" name="to" value="<?= rc_e($filters['to']) ?>"></label>
        <label>Package<select name="package"><option value="">All packages</option><?php foreach ($packages as $package): ?><option value="<?= (int) $package['package_id'] ?>" <?= (int) $filters['package'] === (int) $package['package_id'] ? 'selected' : '' ?>><?= rc_e($package['package_name']) ?></option><?php endforeach; ?></select></label>
        <button class="button" type="submit">Apply filters</button><a class="text-link" href="<?= rc_url('orders') ?>">Clear</a>
    </form>
    <section class="surface owner-table-surface">
        <?php if ($orders): ?><div class="table-wrap"><table><thead><tr><th>Reservation</th><th>Customer</th><th>Package / guests</th><th>Event</th><th>Total</th><th>Deposit / paid / balance</th><th>Status</th><th>Actions</th></tr></thead><tbody>
        <?php foreach ($orders as $order):
            $orderId = (int) $order['id'];
            $lines = $orderItems[$orderId] ?? [];
            $payments = $orderPayments[$orderId] ?? [];
            $detailLines = array_map(static fn ($line) => ($line['customization_details'] ?: 'Selection') . ': ' . ($line['item_name_snapshot'] ?: 'Menu item') . ((float) $line['customization_charge'] > 0 ? ' (+ PHP ' . number_format((float) $line['customization_charge'], 2) . ')' : ''), $lines);
            $paymentLines = array_map(static fn ($payment) => $payment['payment_date'] . ' · PHP ' . $payment['amount'] . ' · ' . $payment['payment_method'] . ($payment['reference_number'] ? ' · Ref ' . $payment['reference_number'] : ''), $payments);
            $detailText = 'Customer ID: ' . ($order['linked_customer_id'] ?: 'Not linked') . "\nCustomer: " . $order['client_name'] . ' · ' . $order['client_mobile'] . ' · ' . $order['client_email'] . "\nVenue: " . $order['delivery_address'] . "\nOccasion: " . ($order['occasion'] ?: 'Not specified') . "\nGuests: " . $order['guest_count'] . "\nSchedule: " . substr((string) $order['event_start_time'], 0, 5) . '–' . substr((string) $order['event_end_time'], 0, 5) . ' · dining ' . substr((string) $order['dining_time'], 0, 5) . "\nPackage: " . ($order['package_name'] ?: $order['dining_tier']) . "\nPackage details: " . ($order['package_description'] ?: 'No description') . "\nMenu choices: " . (implode('; ', $detailLines) ?: 'No itemized selections') . "\nRequests: " . ($order['special_requests'] ?: 'None') . "\nTotal: PHP " . $order['total_price'] . ' · 50% deposit: PHP ' . $order['down_payment_due'] . ' · paid: PHP ' . $order['amount_paid'] . ' · balance: PHP ' . $order['balance_due'] . "\nPayment history: " . (implode('; ', $paymentLines) ?: 'No payments recorded') . ($order['rejected_reason'] ? "\nRejection reason: " . $order['rejected_reason'] : '') . ($order['cancellation_reason'] ? "\nCancellation reason: " . $order['cancellation_reason'] : '') . ($order['status'] === 'Cancelled' ? "\nCancellation fee (included in deposit): PHP " . $order['cancellation_fee'] . "\nRefund due (manual): PHP " . $order['refund_due'] : '');
        ?>
            <tr>
                <td><strong>#RZ-<?= $orderId ?></strong><small>Created <?= rc_e($order['created_at']) ?></small></td>
                <td><?= rc_e($order['client_name']) ?><small><?= rc_e($order['client_mobile']) ?><br><?= rc_e($order['client_email']) ?></small></td>
                <td><?= rc_e($order['package_name'] ?: $order['dining_tier']) ?><small><?= (int) $order['guest_count'] ?> guests</small></td>
                <td><?= rc_e($order['event_date']) ?><small><?= rc_e(substr((string) $order['event_start_time'], 0, 5)) ?>–<?= rc_e(substr((string) $order['event_end_time'], 0, 5)) ?><br><?= rc_e($order['delivery_address']) ?></small></td>
                <td><?= rc_money(rc_cents($order['total_price'])) ?></td>
                <td><?= rc_money(rc_cents($order['down_payment_due'])) ?><small>Paid <?= rc_money(rc_cents($order['amount_paid'])) ?><br>Due <?= rc_money(rc_cents($order['balance_due'])) ?></small></td>
                <td><span class="status status-<?= rc_e(strtolower(str_replace(' ', '-', $order['status']))) ?>"><?= rc_e($order['status']) ?></span><small><?= rc_e($order['payment_status']) ?></small><?php if (in_array($order['status'], ['Confirmed','Processing'], true)): ?><small>Food: <?= rc_e($order['delivery_status'] ?? 'Not Started') ?></small><?php endif; ?></td>
                <td class="action-cell">
                    <button class="text-link" type="button" data-dialog-title="Reservation #RZ-<?= $orderId ?> details" data-dialog-text="<?= rc_e($detailText) ?>">View details</button>
                    <?php if ($order['status'] === 'Pending'): ?>
                        <form method="post" action="<?= rc_e(rc_endpoint()) ?>" data-confirm="Approve reservation #RZ-<?= $orderId ?>? The 50% deposit and schedule are checked by the server."><?= rc_csrf_field() ?><input type="hidden" name="action" value="status"><input type="hidden" name="order_id" value="<?= $orderId ?>"><input type="hidden" name="status" value="Confirmed"><button class="text-link" type="submit">Approve</button></form>
                        <form method="post" action="<?= rc_e(rc_endpoint()) ?>" data-confirm="Reject reservation #RZ-<?= $orderId ?>? A reason is required and will be sent to the customer."><?= rc_csrf_field() ?><input type="hidden" name="action" value="status"><input type="hidden" name="order_id" value="<?= $orderId ?>"><input type="hidden" name="status" value="Rejected"><button class="text-link danger-link" type="submit">Reject</button></form>
                    <?php elseif ($order['status'] === 'Confirmed'): ?>
                        <form method="post" action="<?= rc_e(rc_endpoint()) ?>" data-confirm="Move reservation #RZ-<?= $orderId ?> to preparation?"><?= rc_csrf_field() ?><input type="hidden" name="action" value="status"><input type="hidden" name="order_id" value="<?= $orderId ?>"><input type="hidden" name="status" value="Processing"><button class="text-link" type="submit">Start preparation</button></form>
                    <?php elseif ($order['status'] === 'Processing'): ?>
                        <form method="post" action="<?= rc_e(rc_endpoint()) ?>" data-confirm="Complete reservation #RZ-<?= $orderId ?>? Full payment, Delivered progress, and the event end time are checked by the server."><?= rc_csrf_field() ?><input type="hidden" name="action" value="status"><input type="hidden" name="order_id" value="<?= $orderId ?>"><input type="hidden" name="status" value="Completed"><button class="text-link" type="submit">Complete</button></form>
                    <?php endif; ?>
                    <?php if (in_array($order['status'], ['Confirmed','Processing'], true)): ?><form method="post" action="<?= rc_e(rc_endpoint()) ?>" class="delivery-progress-form"><?= rc_csrf_field() ?><input type="hidden" name="action" value="delivery-status"><input type="hidden" name="order_id" value="<?= $orderId ?>"><label class="sr-only" for="delivery-<?= $orderId ?>">Food delivery progress</label><select id="delivery-<?= $orderId ?>" name="delivery_status"><option <?= ($order['delivery_status'] ?? '') === 'Preparing' ? 'selected' : '' ?>>Preparing</option><option <?= ($order['delivery_status'] ?? '') === 'On the Way' ? 'selected' : '' ?>>On the Way</option><option <?= ($order['delivery_status'] ?? '') === 'Delivered' ? 'selected' : '' ?>>Delivered</option></select><button class="text-link" type="submit">Update food progress</button></form><?php endif; ?>
                    <?php if (in_array($order['status'], ['Pending','Confirmed','Processing'], true) && (float) $order['balance_due'] > 0): ?><button class="text-link" type="button" data-payment="<?= $orderId ?>" data-balance="<?= rc_e($order['balance_due']) ?>">Record payment</button><?php endif; ?>
                    <?php if (in_array($order['status'], ['Pending','Confirmed','Processing'], true)): ?><form method="post" action="<?= rc_e(rc_endpoint()) ?>" data-confirm="Cancel reservation #RZ-<?= $orderId ?>? The 10% cancellation fee is included in the non-refundable 50% deposit. Any paid amount above the deposit is refunded manually outside this system."><?= rc_csrf_field() ?><input type="hidden" name="action" value="status"><input type="hidden" name="order_id" value="<?= $orderId ?>"><input type="hidden" name="status" value="Cancelled"><button class="text-link danger-link" type="submit">Cancel</button></form><?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?></tbody></table></div><?php else: ?><div class="empty-state"><strong>No matching reservations</strong>Change the filters or search text to view other orders.</div><?php endif; ?>
    </section>
</section>
<dialog class="app-dialog" id="payment-dialog"><form method="dialog"><button class="dialog-close" aria-label="Close dialog">×</button></form><h2>Record offline payment</h2><p class="muted">This records a payment; it does not contact a payment gateway.</p><form method="post" action="<?= rc_e(rc_endpoint()) ?>" class="form-stack" id="payment-form"><?= rc_csrf_field() ?><input type="hidden" name="action" value="payment"><input type="hidden" name="order_id" id="payment-order-id"><div class="field"><label for="payment-amount">Amount (PHP)</label><input class="input-field" id="payment-amount" name="amount" type="number" min="0.01" step="0.01" required></div><div class="field"><label for="payment-method">Payment method</label><select class="input-field" id="payment-method" name="payment_method" required><option>Cash</option><option>GCash</option><option>Bank Transfer</option><option>Check</option></select></div><div class="field"><label for="payment-reference">Receipt/reference</label><input class="input-field" id="payment-reference" name="reference_number" maxlength="120"></div><button class="button" type="submit">Save payment record</button></form></dialog>
