<?php
$pageTitle = 'Dashboard';
$summary = $ownerSummary;
$chartMax = max(1, ...array_map(static fn ($row) => (float) $row['total'], $salesTrend ?: [['total' => 0]]));
$greeting = (int) date('G') < 12 ? 'Good morning' : ((int) date('G') < 18 ? 'Good afternoon' : 'Good evening');
?>
<section class="owner-dashboard"><header class="owner-welcome"><div><span class="eyebrow">Owner overview</span><h1><?= $greeting ?>, <?= rc_e($user['full_name']) ?>.</h1><p>Here is the current business activity from reservations, payments, events, and customer feedback.</p></div><a class="button" href="<?= rc_url('orders', ['status' => 'Pending']) ?>">Review pending orders <span class="button-count"><?= (int) $summary['pending_orders'] ?></span></a></header>
<div class="owner-metrics"><a class="owner-metric metric-warm" href="<?= rc_url('orders', ['status' => 'Pending']) ?>"><span>Pending orders</span><strong><?= (int) $summary['pending_orders'] ?></strong><small>Awaiting review</small></a><a class="owner-metric" href="<?= rc_url('orders', ['status' => 'Confirmed']) ?>"><span>Confirmed</span><strong><?= (int) $summary['confirmed_orders'] ?></strong><small>Accepted reservations</small></a><a class="owner-metric" href="<?= rc_url('operations') ?>"><span>Upcoming events</span><strong><?= (int) $upcomingEventsCount ?></strong><small><?= (int) $todayEvents ?> scheduled today</small></a><a class="owner-metric" href="<?= rc_url('reports') ?>"><span>Payments collected</span><strong><?= rc_money(rc_cents($summary['collected'])) ?></strong><small>Recorded transactions</small></a><a class="owner-metric" href="<?= rc_url('reports') ?>"><span>Outstanding balance</span><strong><?= rc_money(rc_cents($summary['outstanding'])) ?></strong><small>Across active bookings</small></a><a class="owner-metric" href="<?= rc_url('feedback-admin') ?>"><span>New feedback</span><strong><?= (int) $newFeedbackCount ?></strong><small><?= (int) $unreadNotifications ?> owner alerts</small></a></div>
<div class="owner-dashboard-grid"><section class="surface sales-surface"><div class="surface-heading"><div><span class="eyebrow section-eyebrow">Recorded transactions</span><h2>Payments collected</h2></div><form method="get" action="<?= rc_e(rc_endpoint()) ?>" class="period-form"><input type="hidden" name="page" value="owner"><select name="period" aria-label="Sales chart period" onchange="this.form.submit()"><option value="today" <?= $period === 'today' ? 'selected' : '' ?>>Today</option><option value="week" <?= $period === 'week' ? 'selected' : '' ?>>This week</option><option value="month" <?= $period === 'month' ? 'selected' : '' ?>>This month</option><option value="year" <?= $period === 'year' ? 'selected' : '' ?>>This year</option></select></form></div><?php if ($salesTrend): ?><div class="sales-chart" role="img" aria-label="Recorded payments by <?= rc_e($period) ?> period"><?php foreach ($salesTrend as $entry): $height = max(4, (int) round(((float) $entry['total'] / $chartMax) * 100)); ?><div class="sales-bar-group"><span class="sales-bar-value"><?= rc_money(rc_cents($entry['total'])) ?></span><div class="sales-bar" style="height:<?= $height ?>%"></div><span class="sales-bar-label"><?= rc_e($entry['label']) ?></span></div><?php endforeach; ?></div><?php else: ?><div class="chart-empty"><strong>No recorded payments in this period.</strong><span>Payment activity appears after authorized owner record a transaction.</span></div><?php endif; ?><div class="sales-foot"><span>Booked sales</span><strong><?= rc_money(rc_cents($summary['booked_sales'])) ?></strong><span>Completed reservations</span><strong><?= (int) $summary['completed_orders'] ?></strong></div></section>
<section class="surface alerts-surface" id="owner-alerts">
<div class="surface-heading"><div><span class="eyebrow section-eyebrow">Needs attention</span><h2>Owner alerts</h2></div><span class="alert-count"><?= (int) $unreadNotifications ?></span></div>
<?php if ((int) $summary['pending_orders'] > 0): ?><a class="owner-alert" href="<?= rc_url('orders', ['status' => 'Pending']) ?>"><span class="alert-mark">!</span><span><strong><?= (int) $summary['pending_orders'] ?> reservation<?= (int) $summary['pending_orders'] === 1 ? '' : 's' ?> need review</strong><small>Open the pending order queue</small></span><b>→</b></a><?php endif; ?>
<?php if ($newFeedbackCount > 0): ?><a class="owner-alert" href="<?= rc_url('feedback-admin') ?>"><span class="alert-mark">☆</span><span><strong><?= (int) $newFeedbackCount ?> new feedback response<?= (int) $newFeedbackCount === 1 ? '' : 's' ?></strong><small>Read and mark feedback reviewed</small></span><b>→</b></a><?php endif; ?>
<?php if ($todayEvents > 0): ?><a class="owner-alert" href="<?= rc_url('operations', ['view' => 'day', 'date' => date('Y-m-d')]) ?>"><span class="alert-mark">◷</span><span><strong><?= (int) $todayEvents ?> confirmed event<?= (int) $todayEvents === 1 ? '' : 's' ?> today</strong><small>Check event details and payment status</small></span><b>→</b></a><?php endif; ?>
<?php if ($unreadNotifications > 0): ?><form method="post" action="<?= rc_e(rc_endpoint()) ?>" class="inline-form"><?= rc_csrf_field() ?><input type="hidden" name="action" value="mark-owner-read"><button class="button button-secondary" type="submit">Mark owner notifications read</button></form><?php endif; ?>
<?php if ((int) $summary['pending_orders'] === 0 && !$newFeedbackCount && !$todayEvents): ?><div class="chart-empty"><strong>Nothing urgent right now.</strong><span>New reservations and feedback will appear here.</span></div><?php endif; ?></section></div>
<div class="owner-dashboard-grid"><section class="surface"><div class="surface-heading"><div><span class="eyebrow section-eyebrow">Scheduling</span><h2>Upcoming events</h2></div><a class="text-link" href="<?= rc_url('operations') ?>">Open operations →</a></div><?php if ($upcomingEvents): ?><div class="table-wrap"><table><thead><tr><th>Customer</th><th>Date / time</th><th>Package</th><th>Guests</th><th>Venue</th><th>Payment</th></tr></thead><tbody><?php foreach ($upcomingEvents as $event): ?><tr><td><?= rc_e($event['client_name']) ?><small><?= rc_e($event['client_mobile']) ?></small></td><td><?= rc_e($event['event_date']) ?><small><?= rc_e(substr($event['start_time'],0,5)) ?>–<?= rc_e(substr($event['end_time'],0,5)) ?></small></td><td><?= rc_e($event['package_name'] ?: 'Package') ?></td><td><?= (int) $event['guest_count'] ?></td><td><?= rc_e($event['venue']) ?></td><td><?= rc_e($event['payment_status']) ?><small>Due <?= rc_money(rc_cents($event['balance_due'])) ?></small></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><div class="chart-empty"><strong>No confirmed upcoming events.</strong><span>Approved reservations will appear here.</span></div><?php endif; ?></section>
<section class="surface"><div class="surface-heading"><div><span class="eyebrow section-eyebrow">Latest requests</span><h2>Recent orders</h2></div><a class="text-link" href="<?= rc_url('orders') ?>">All orders →</a></div><?php if ($recentOrders): ?><div class="recent-order-list"><?php foreach ($recentOrders as $order): ?><a href="<?= rc_url('orders', ['q' => (int) $order['id']]) ?>" class="recent-order"><span class="recent-order-id">#RZ-<?= (int) $order['id'] ?></span><span class="recent-order-main"><strong><?= rc_e($order['client_name']) ?></strong><small><?= rc_e($order['package_name'] ?: 'Catering request') ?> · <?= rc_e($order['event_date']) ?></small></span><span class="status status-<?= rc_e(strtolower($order['status'])) ?>"><?= rc_e($order['status']) ?></span></a><?php endforeach; ?></div><?php else: ?><div class="chart-empty"><strong>No orders yet.</strong><span>Customer reservations will be listed here.</span></div><?php endif; ?></section></div></section>
