<?php $pageTitle = 'Reservation details'; ?>
<section class="page-intro"><div class="intro-inner"><span class="eyebrow">Reservation #RZ-<?= (int) $order['id'] ?></span><h1><?= rc_e($order['package_name'] ?: $order['dining_tier']) ?></h1><p>Submitted <?= rc_e($order['created_at']) ?>. Current status: <strong><?= rc_e($order['status']) ?></strong>.</p></div></section>
<section class="content-section">
    <div class="detail-grid">
        <section class="surface"><div class="surface-heading"><h2>Event details</h2><span class="status status-<?= rc_e(strtolower(str_replace(' ', '-', $order['status']))) ?>"><?= rc_e($order['status']) ?></span></div><dl class="detail-list"><dt>Event date</dt><dd><?= rc_e($order['event_date']) ?></dd><dt>Schedule</dt><dd><?= rc_e(substr((string) $order['event_start_time'], 0, 5)) ?>–<?= rc_e(substr((string) $order['event_end_time'], 0, 5)) ?> · Dining <?= rc_e(substr((string) $order['dining_time'], 0, 5)) ?></dd><dt>Venue</dt><dd><?= rc_e($order['delivery_address']) ?></dd><dt>Guests</dt><dd><?= (int) $order['guest_count'] ?></dd><dt>Occasion</dt><dd><?= rc_e($order['occasion'] ?: 'Not specified') ?></dd><dt>Theme</dt><dd><?= rc_e($order['motif'] ?: 'Not specified') ?></dd><dt>Requests</dt><dd><?= nl2br(rc_e($order['special_requests'] ?: 'None')) ?></dd></dl></section>
        <section class="surface"><div class="surface-heading"><h2>Order and payment</h2><span><?= rc_e($order['payment_status']) ?></span></div><dl class="detail-list"><dt>Order total</dt><dd><?= rc_money(rc_cents($order['total_price'])) ?></dd><dt>50% deposit required</dt><dd><?= rc_money(rc_cents($order['down_payment_due'])) ?></dd><dt>Amount paid</dt><dd><?= rc_money(rc_cents($order['amount_paid'])) ?></dd><dt>Remaining balance</dt><dd><?= rc_money(rc_cents($order['balance_due'])) ?></dd><?php if ($order['status'] === 'Cancelled'): ?><dt>Cancellation fee (included in deposit)</dt><dd><?= rc_money(rc_cents($order['cancellation_fee'])) ?></dd><dt>Refund due</dt><dd><?= rc_money(rc_cents($order['refund_due'])) ?> · handled manually</dd><?php endif; ?></dl><p class="muted">Payments are recorded by the owner. Do not send payment details through this page.</p><h3>Selected options</h3><?php if ($orderItems): ?><ul class="selected-lines"><?php foreach ($orderItems as $item): ?><li><?= rc_e($item['customization_details']) ?>: <?= rc_e($item['item_name_snapshot'] ?: 'Menu selection') ?> · <?= (int)$item['quantity'] ?> × <?= rc_money(rc_cents($item['unit_price_snapshot'])) ?><?= (float) $item['customization_charge'] > 0 ? ' (+' . rc_money(rc_cents($item['customization_charge'])) . ')' : '' ?></li><?php endforeach; ?></ul><?php else: ?><p class="muted">Package choices are included in the reservation total.</p><?php endif; ?></section>
    </div>
    <?php if (in_array($order['status'], ['Confirmed', 'Processing', 'Completed'], true)): ?><section class="surface"><div class="surface-heading"><h2>Food preparation and delivery</h2><span><?= rc_e($order['delivery_status'] ?? 'Not Started') ?></span></div><p>The owner updates this as your food is prepared and travels to the venue. Each update also appears in your in-site notifications.</p></section><?php endif; ?>
    <?php if ($order['status'] === 'Completed' && !$feedback): ?><section class="surface feedback-surface"><h2>How was your catering service?</h2><form method="post" action="<?= rc_e(rc_endpoint()) ?>" class="booking-grid"><?= rc_csrf_field() ?><input type="hidden" name="action" value="feedback"><input type="hidden" name="order_id" value="<?= (int) $order['id'] ?>"><div class="field"><label for="rating">Rating</label><select class="input-field" name="rating" id="rating" required><option value="">Select 1–5</option><?php for ($rating = 5; $rating >= 1; $rating--): ?><option value="<?= $rating ?>"><?= $rating ?> / 5</option><?php endfor; ?></select></div><div class="field field-wide"><label for="comments">Feedback</label><textarea class="input-field" name="comments" id="comments" maxlength="3000" required></textarea></div><div class="field-wide"><button class="button" type="submit">Submit feedback</button></div></form></section><?php elseif ($feedback): ?><section class="surface"><h2>Feedback submitted</h2><p><?= (int) $feedback['rating'] ?> / 5 · <?= rc_e($feedback['comments']) ?></p></section><?php endif; ?>
    <a class="text-link" href="<?= rc_url('dashboard') ?>">← Back to dashboard</a>
</section>
