<?php
$pageTitle = 'Reserve catering';
$packages = $packages ?? []; $items = $items ?? []; $packageOptions = $packageOptions ?? [];
$oldReservation = is_array($reservationOld ?? null) ? $reservationOld : [];
$oldValue = static function (string $key, string $default = '') use ($oldReservation): string { $value = $oldReservation[$key] ?? $default; return rc_e(is_scalar($value) ? (string) $value : $default); };
$oldItems = is_array($oldReservation['items'] ?? null) ? $oldReservation['items'] : [];
$oldOptions = is_array($oldReservation['options'] ?? null) ? $oldReservation['options'] : [];
$oldOptionSelected = static function (string $group, int $id, bool $default = false) use ($oldOptions): bool {
    if (!array_key_exists($group, $oldOptions)) return $default;
    $values = is_array($oldOptions[$group]) ? $oldOptions[$group] : [$oldOptions[$group]];
    return in_array((string) $id, array_map(static fn ($value) => is_scalar($value) ? (string) $value : '', $values), true);
};
$requestedPackage = (int) ($requestedPackage ?? 0);
if ($requestedPackage < 1) $requestedPackage = (int) ($_GET['package'] ?? $oldReservation['package_id'] ?? 0);
$initialOrderType = '';
foreach ($packages as $p) if ((int)$p['package_id']===$requestedPackage) { $initialOrderType = in_array(($p['package_type']??'custom'), ['packed_meal','buffet','custom'], true) ? $p['package_type'] : 'custom'; break; }
if ($requestedPackage < 1) {
    $oldOrderType = (string) ($oldReservation['order_type'] ?? $_GET['order_type'] ?? '');
    if (in_array($oldOrderType, ['alacarte','packed_meal','buffet','custom'], true)) $initialOrderType = $oldOrderType;
}
$groups = [];
foreach ($packageOptions as $option) {
    if (($option['package_type'] ?? '') === 'packed_meal' && $option['component_type'] === 'rice') continue;
    $groups[(int)$option['package_id']][$option['option_group']][] = $option;
}
$componentOrder = ['main_dish'=>0,'side_dish'=>1,'dessert'=>2,'salad'=>3,'rice'=>4,'drink'=>5,'add_on'=>6,'other'=>7];
foreach ($groups as &$packageGroups) {
    uasort($packageGroups, static function ($a, $b) use ($componentOrder) { return ($componentOrder[$a[0]['component_type']] ?? 8) <=> ($componentOrder[$b[0]['component_type']] ?? 8); });
}
unset($packageGroups);
$unitLabels = ['tray_25_35pax'=>'Tray · serves 25–35','per_pc'=>'Per piece','per_box'=>'Per box','per_tray'=>'Per tray','per_layer'=>'Per layer','per_slice'=>'Per slice','per_person'=>'Per person','each'=>'Each'];
?>
<section class="page-intro"><div class="intro-inner"><span class="eyebrow">Plan your event</span><h1>Make a reservation</h1><p>Choose a food package, buffet, packed lunch, or food trays first. Buffet dishes start with the set selections and can be changed. Packed lunches include steamed rice.</p></div></section>
<section class="booking-section"><div class="booking-inner"><form class="booking-form" method="post" action="<?= rc_e(rc_endpoint()) ?>" data-order-form>
<?= rc_csrf_field() ?><input type="hidden" name="action" value="reserve">
<h2>Choose your catering style</h2>
<div class="booking-grid"><div class="field field-wide"><label for="order-type">What would you like to order?</label><select class="input-field" id="order-type" name="order_type" required><option value="" <?= $initialOrderType===''?'selected':'' ?>>Choose a service</option><option value="custom" <?= $initialOrderType==='custom'?'selected':'' ?>>Food package</option><option value="buffet" <?= $initialOrderType==='buffet'?'selected':'' ?>>Lunch / dinner buffet</option><option value="packed_meal" <?= $initialOrderType==='packed_meal'?'selected':'' ?>>Packed lunch</option><option value="alacarte" <?= $initialOrderType==='alacarte'?'selected':'' ?>>Food trays / individual dishes</option></select></div>
<div class="field field-wide" data-package-picker hidden><label for="package">Food package</label><select class="input-field" name="package_id" id="package"><option value="">Select a package</option><?php foreach ($packages as $package): ?><option value="<?= (int)$package['package_id'] ?>" data-package-type="<?= rc_e($package['package_type'] ?? 'custom') ?>" data-minimum="<?= max(1,(int)$package['minimum_guests']) ?>" data-maximum="<?= rc_e((string)($package['maximum_guests'] ?? '')) ?>" data-price="<?= rc_e($package['package_price']) ?>" data-pricing="<?= rc_e($package['price_type']) ?>" <?= $requestedPackage === (int)$package['package_id'] ? 'selected' : '' ?>><?= rc_e(($package['set_name'] ?? '') ?: $package['package_name']) ?> · <?= rc_money(rc_cents($package['package_price'])) ?> <?= $package['price_type']==='Per Person' ? '/ person' : 'package' ?></option><?php endforeach; ?></select><small class="package-empty-note" data-package-empty role="status" hidden>No active food packages are configured yet. Choose buffet or packed lunch, or ask the owner to add a food package under Owner → Packages.</small></div>
<div class="field"><label for="guest-count">Number of guests</label><input class="input-field" id="guest-count" name="guest_count" type="number" min="1" max="10000" value="<?= $oldValue('guest_count','50') ?>" required></div>
<?php foreach ($packages as $package): foreach ($groups[(int)$package['package_id']] ?? [] as $group=>$options): $isRequired=$options[0]['selection_rule']==='Required One'; $limit=$options[0]['component_type']==='add_on' ? 20 : (($options[0]['component_type']==='main_dish' && ($package['package_type']??'')==='packed_meal' && ($package['set_name']??'')==='Tier D') ? 2 : 1); ?>
<fieldset class="field field-wide package-options" data-package-options="<?= (int)$package['package_id'] ?>" data-option-limit="<?= $limit ?>" hidden><legend><?php if (($package['package_type']??'')==='buffet' && str_starts_with((string)$group,'Included: ')): ?><?= rc_e(ucwords(str_replace('_',' ',(string)$options[0]['component_type']))) ?> · included: <?= rc_e(substr((string)$group,10)) ?> · choose a replacement if desired<?php else: ?><?= rc_e(ucwords(str_replace('_',' ',(string)$options[0]['component_type']))) ?><?= $isRequired ? ' · choose one' : ' · choose up to '.$limit ?><?php endif; ?></legend><div class="option-grid"><?php foreach ($options as $option): $inputType=$isRequired ? 'radio' : 'checkbox'; $defaultSelection=($package['package_type']??'')==='buffet' && str_starts_with((string)$group,'Included: ') && strcasecmp((string)$option['name'],substr((string)$group,10))===0; $isSelected=$oldOptionSelected((string)$group,(int)$option['id'],$defaultSelection); ?><label class="option-choice"><input type="<?= $inputType ?>" name="options[<?= rc_e($group) ?>]<?= $inputType==='checkbox'?'[]':'' ?>" value="<?= (int)$option['id'] ?>" data-charge="<?= rc_e($option['additional_charge']) ?>" data-charge-type="<?= rc_e($option['charge_type'] ?? 'per_event') ?>" <?= $isRequired ? 'required' : '' ?> <?= $isSelected?'checked':'' ?>><span><strong><?= rc_e($option['name']) ?></strong><small><?= rc_e($option['description'] ?: $option['category']) ?><?= rc_cents($option['additional_charge']) > 0 ? ' · +' . rc_money(rc_cents($option['additional_charge'])) . (($option['charge_type']??'')==='per_person'?' per person':'') : '' ?></small></span></label><?php endforeach; ?></div></fieldset>
<?php endforeach; endforeach; ?>
<?php foreach ($packages as $package): if (($package['package_type'] ?? '') === 'packed_meal'): ?><fieldset class="field field-wide package-options package-default-inclusion" data-package-options="<?= (int)$package['package_id'] ?>" hidden><legend>Rice · included</legend><p>Steamed rice is included in the packed lunch price and does not need to be selected.</p></fieldset><?php endif; endforeach; ?>
<fieldset class="field field-wide" data-alacarte hidden><legend>Choose food trays and quantities</legend><div class="package-choice-list"><?php foreach ($items as $item): ?><div class="package-choice-row"><span><strong><?= rc_e($item['name']) ?></strong><small><?= rc_e($item['description'] ?: $item['category']) ?> · <?= rc_e($unitLabels[$item['unit_type'] ?? 'tray_25_35pax'] ?? 'Each') ?> · <?= rc_money(rc_cents($item['price'])) ?></small><?php if (($item['unit_type'] ?? '') === 'tray_25_35pax'): ?><small data-tray-guidance>Choose tray quantity for your guest count.</small><?php endif; ?></span><label class="option-charge">Quantity<input name="items[<?= (int)$item['id'] ?>]" type="number" min="0" max="1000" step="1" value="<?= rc_e(isset($oldItems[$item['id']]) && is_scalar($oldItems[$item['id']]) ? (string)$oldItems[$item['id']] : '0') ?>" data-item-price="<?= rc_e($item['price']) ?>"></label></div><?php endforeach; ?></div></fieldset>
<div class="field"><label for="event-date">Event date</label><input class="input-field" id="event-date" name="event_date" type="date" min="<?= date('Y-m-d') ?>" value="<?= $oldValue('event_date') ?>" required></div><div class="field"><label for="event-start">Start time</label><input class="input-field" id="event-start" name="event_start_time" type="time" value="<?= $oldValue('event_start_time') ?>" required></div><div class="field"><label for="event-end">End time</label><input class="input-field" id="event-end" name="event_end_time" type="time" value="<?= $oldValue('event_end_time') ?>" required></div><div class="field"><label for="dining-time">Dining time</label><input class="input-field" id="dining-time" name="dining_time" type="time" value="<?= $oldValue('dining_time') ?>" required></div><div class="field"><label for="occasion">Occasion</label><input class="input-field" id="occasion" name="occasion" maxlength="100" placeholder="Birthday, wedding, etc." value="<?= $oldValue('occasion') ?>"></div><div class="field field-wide"><label for="venue">Venue and address</label><input class="input-field" id="venue" name="venue" maxlength="500" value="<?= $oldValue('venue') ?>" required></div><div class="field"><label for="motif">Motif / theme</label><input class="input-field" id="motif" name="motif" maxlength="160" value="<?= $oldValue('motif') ?>"></div><div class="field field-wide"><label for="requests">Special requests</label><textarea class="input-field" id="requests" name="special_requests" maxlength="5000"><?= $oldValue('special_requests') ?></textarea></div>
<?php if ($customer): ?><div class="field field-wide"><label>Contact</label><p class="muted">Using <?= rc_e($customer['full_name']) ?> · <?= rc_e($customer['email']) ?> · <?= rc_e($customer['contact_number']) ?>. Update these details from your account dashboard.</p></div><?php else: ?><div class="field field-wide"><h3>Contact details</h3><p class="muted">You can place this order without an account. These details let the owner contact you about your booking.</p></div><div class="field"><label for="client-name">Full name</label><input class="input-field" id="client-name" name="client_name" maxlength="120" autocomplete="name" value="<?= $oldValue('client_name') ?>" required></div><div class="field"><label for="client-email">Email</label><input class="input-field" id="client-email" name="client_email" type="email" maxlength="254" autocomplete="email" value="<?= $oldValue('client_email') ?>" required></div><div class="field"><label for="client-mobile">Mobile number</label><input class="input-field" id="client-mobile" name="client_mobile" type="tel" maxlength="30" autocomplete="tel" value="<?= $oldValue('client_mobile') ?>" required></div><?php endif; ?></div>
<div class="price-estimate" id="price-estimate" aria-live="polite">Choose dishes or a package to see the estimated total and 50% deposit.</div><p class="submit-note">No payment is processed online. The owner records Cash, GCash, Bank Transfer, or Check payments manually. Event confirmation requires the 50% deposit and schedule approval.</p><div class="policy-accept field-wide"><p><strong>Cancellation policy:</strong> the 50% deposit is non-refundable and includes the 10% cancellation fee. Any amount paid above the deposit is refunded manually outside this system.</p><label><input type="checkbox" name="accept_cancellation_policy" value="1" <?= !empty($oldReservation['accept_cancellation_policy']) ? 'checked' : '' ?> required> I have read and agree to this cancellation policy.</label></div><?php if (!$customer): ?><p class="muted">Want reservation status updates and the ability to review completed bookings? <a class="text-link" href="<?= rc_url('register') ?>">Create a customer account</a> before booking.</p><?php endif; ?><button class="button form-submit" type="submit">Submit reservation</button></form></div></section>
